"use client";
// import type { Metadata } from "next";

import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import { StPeterProvider } from "st-peter-ui";

//@ts-ignore
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import BottomNav from "@/components/ui/bottom-nav";
import RootLayoutClient from "./root-layout-client";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "E-store V2",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const noLayoutRoutes = [""];

  const hideLayout = noLayoutRoutes.includes(pathname);
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>St. Peter E-Store</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body style={{ overflowX: "hidden" }}>
        <RootLayoutClient>
          <StPeterProvider theme="green">
            {!hideLayout && <Navbar />}
            {children}
            {!hideLayout && <BottomNav/>}
            {!hideLayout && <Footer />}
          </StPeterProvider>
        </RootLayoutClient>
      </body>
    </html>
  );
}
